version: "3.9"
services:

  postgres:
    image: postgres:12
    environment:
      - POSTGRES_DB=gestionclient
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    networks:
      - my-network
    volumes:
      - db:/var/lib/pgadmin

  client:
    container_name: client
    build: ./GestionDesClients
    image: "client-service"
    ports:
      - "8086:8086"
    hostname: localhost
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/gestionclient
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
    depends_on:
      - discovery
      - postgres
    networks:
      - my-network

  discovery:
    build: ./EurekaServer
    ports:
      - "8761:8761"
    image: "discovery-service"
    networks:
      - my-network

  vol:
    hostname: localhost
    build: 
      context: ./GestionVols
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka
    ports:
      - "8082:8082"
    depends_on:
      - discovery

networks:
  my-network:
    driver: bridge

volumes:
  db:
