version: "3.9"
services:

  postgres:
    image: postgres:12
    environment:
      - POSTGRES_DB=gestionclient
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    networks:
      - my-network

  client:
    container_name: client
    build: D:\studies\esprit\2eme\microservice\Projet\GestionDesClients
    image: "client-service"
    ports:
      - "8086:8086"
    hostname: localhost
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/gestionclient
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
    depends_on:
      - discovery
      - postgres
    networks:
      - my-network

  discovery:
    build: D:\studies\esprit\2eme\microservice\Projet\EurekaServer
    ports:
      - "8761:8761"
    image: "discovery-service"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
